In [1]:
print("Hello Pallavi!")

Hello Pallavi!

# Capstone Project - Python Fundamentals
## Task 1: Create DataFrames

In [3]:
# Import required libraries
import pandas as pd
import numpy as np

In [4]:
# Creating Employee DataFrame
employee = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
})

# Display the dataframe
employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [5]:
# Creating Seniority DataFrame
seniority = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
})

# Display the dataframe
seniority

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [6]:
# Creating Project DataFrame
project = pd.DataFrame({
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project1","Project2","Project3","Project4","Project5","Project6","Project7","Project8","Project9","Project10","Project11","Project12","Project13","Project14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
})

# Display the dataframe
project

      ID    Project       Cost    Status
0   A001   Project1  1002000.0  Finished
1   A002   Project2  2000000.0   Ongoing
2   A003   Project3  4500000.0  Finished
3   A004   Project4  5500000.0   Ongoing
4   A005   Project5        NaN  Finished
5   A002   Project6   680000.0    Failed
6   A005   Project7   400000.0  Finished
7   A003   Project8   350000.0    Failed
8   A001   Project9        NaN   Ongoing
9   A003  Project10   300000.0  Finished
10  A001  Project11  2000000.0    Failed
11  A004  Project12  1000000.0   Ongoing
12  A004  Project13  3000000.0  Finished
13  A005  Project14   200000.0  Finished

In [8]:
# Saving all dataframes as CSV files
employee.to_csv("employee.csv", index=False)
seniority.to_csv("seniority.csv", index=False)
project.to_csv("project.csv", index=False)

In [9]:
import os
os.listdir()

['.pythonstartup.py',
 '.local',
 'seniority.csv',
 '.npm',
 '.vimrc',
 '.anaconda',
 '.virtualenvs',
 '.jupyter',
 'Untitled.ipynb',
 'employee.csv',
 '.ipynb_checkpoints',
 'project.csv',
 '.gitconfig',
 'README.ipynb',
 '.conda',
 '.profile',
 'anaconda_projects',
 '.bashrc',
 '.ipython']

In [10]:
# Load project data from CSV
project = pd.read_csv("project.csv")

project

      ID    Project       Cost    Status
0   A001   Project1  1002000.0  Finished
1   A002   Project2  2000000.0   Ongoing
2   A003   Project3  4500000.0  Finished
3   A004   Project4  5500000.0   Ongoing
4   A005   Project5        NaN  Finished
5   A002   Project6   680000.0    Failed
6   A005   Project7   400000.0  Finished
7   A003   Project8   350000.0    Failed
8   A001   Project9        NaN   Ongoing
9   A003  Project10   300000.0  Finished
10  A001  Project11  2000000.0    Failed
11  A004  Project12  1000000.0   Ongoing
12  A004  Project13  3000000.0  Finished
13  A005  Project14   200000.0  Finished

In [11]:
# Convert cost column into list
cost_list = project["Cost"].tolist()

# Loop to replace missing values
for i in range(len(cost_list)):
    if pd.isna(cost_list[i]):  # check missing value
        avg = np.nanmean(cost_list[:i])  # running average
        cost_list[i] = avg  # replace with avg

# Update dataframe
project["Cost"] = cost_list

# Show updated dataframe
project

      ID    Project       Cost    Status
0   A001   Project1  1002000.0  Finished
1   A002   Project2  2000000.0   Ongoing
2   A003   Project3  4500000.0  Finished
3   A004   Project4  5500000.0   Ongoing
4   A005   Project5  3250500.0  Finished
5   A002   Project6   680000.0    Failed
6   A005   Project7   400000.0  Finished
7   A003   Project8   350000.0    Failed
8   A001   Project9  2210312.5   Ongoing
9   A003  Project10   300000.0  Finished
10  A001  Project11  2000000.0    Failed
11  A004  Project12  1000000.0   Ongoing
12  A004  Project13  3000000.0  Finished
13  A005  Project14   200000.0  Finished

In [12]:
# Load employee data
employee = pd.read_csv("employee.csv")

employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [13]:
# Split Name into First Name and Last Name
employee[["First Name", "Last Name"]] = employee["Name"].str.split(" ", expand=True)

# Drop original Name column
employee.drop("Name", axis=1, inplace=True)

# Show updated dataframe
employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [15]:
# Load all datasets
employee = pd.read_csv("employee.csv")
seniority = pd.read_csv("seniority.csv")
project = pd.read_csv("project.csv")

In [16]:
# Merge employee and seniority
final = pd.merge(employee, seniority, on="ID")

# Merge with project
final = pd.merge(final, project, on="ID")

# Display final dataframe
final

,ID,Name,Gender,City,Age,Designation Level,Project,Cost,Status
0,A001,John Alter,M,Paris,25,2,Project1,1002000.0,Finished
1,A001,John Alter,M,Paris,25,2,Project9,NaN,Ongoing
2,A001,John Alter,M,Paris,25,2,Project11,2000000.0,Failed
3,A002,Alice Luxumberg,F,London,27,2,Project2,2000000.0,Ongoing
4,A002,Alice Luxumberg,F,London,27,2,Project6,680000.0,Failed
5,A003,Tom Sabestine,M,Berlin,29,3,Project3,4500000.0,Finished
6,A003,Tom Sabestine,M,Berlin,29,3,Project8,350000.0,Failed
7,A003,Tom Sabestine,M,Berlin,29,3,Project10,300000.0,Finished
8,A004,Nina Adgra,F,Newyork,31,2,Project4,5500000.0,Ongoing
9,A004,Nina Adgra,F,Newyork,31,2,Project12,1000000.0,Ongoing
10,A004,Nina Adgra,F,Newyork,31,2,Project13,3000000.0,Finished
11,A005,Amy Johny,F,Madrid,30,3,Project5,NaN,Finished
12,A005,Amy Johny,F,Madrid,30,3,Project7,400000.0,Finished
13,A005,Amy Johny,F,Madrid,30,3,Project14,200000.0,Finished

In [17]:
# Add bonus column (5% if project is Finished)
final["Bonus"] = np.where(final["Status"] == "Finished",
                          final["Cost"] * 0.05,
                          0)

# Show updated dataframe
final

,ID,Name,Gender,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,John Alter,M,Paris,25,2,Project1,1002000.0,Finished,50100.0
1,A001,John Alter,M,Paris,25,2,Project9,NaN,Ongoing,0.0
2,A001,John Alter,M,Paris,25,2,Project11,2000000.0,Failed,0.0
3,A002,Alice Luxumberg,F,London,27,2,Project2,2000000.0,Ongoing,0.0
4,A002,Alice Luxumberg,F,London,27,2,Project6,680000.0,Failed,0.0
5,A003,Tom Sabestine,M,Berlin,29,3,Project3,4500000.0,Finished,225000.0
6,A003,Tom Sabestine,M,Berlin,29,3,Project8,350000.0,Failed,0.0
7,A003,Tom Sabestine,M,Berlin,29,3,Project10,300000.0,Finished,15000.0
8,A004,Nina Adgra,F,Newyork,31,2,Project4,5500000.0,Ongoing,0.0
9,A004,Nina Adgra,F,Newyork,31,2,Project12,1000000.0,Ongoing,0.0
10,A004,Nina Adgra,F,Newyork,31,2,Project13,3000000.0,Finished,150000.0
11,A005,Amy Johny,F,Madrid,30,3,Project5,NaN,Finished,NaN
12,A005,Amy Johny,F,Madrid,30,3,Project7,400000.0,Finished,20000.0
13,A005,Amy Johny,F,Madrid,30,3,Project14,200000.0,Finished,10000.0

In [18]:
# Demote designation level by 1 where project failed
final.loc[final["Status"] == "Failed", "Designation Level"] += 1

# Remove employees with designation level > 4
final = final[final["Designation Level"] <= 4]

# Show updated dataframe
final

,ID,Name,Gender,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,John Alter,M,Paris,25,2,Project1,1002000.0,Finished,50100.0
1,A001,John Alter,M,Paris,25,2,Project9,NaN,Ongoing,0.0
2,A001,John Alter,M,Paris,25,3,Project11,2000000.0,Failed,0.0
3,A002,Alice Luxumberg,F,London,27,2,Project2,2000000.0,Ongoing,0.0
4,A002,Alice Luxumberg,F,London,27,3,Project6,680000.0,Failed,0.0
5,A003,Tom Sabestine,M,Berlin,29,3,Project3,4500000.0,Finished,225000.0
6,A003,Tom Sabestine,M,Berlin,29,4,Project8,350000.0,Failed,0.0
7,A003,Tom Sabestine,M,Berlin,29,3,Project10,300000.0,Finished,15000.0
8,A004,Nina Adgra,F,Newyork,31,2,Project4,5500000.0,Ongoing,0.0
9,A004,Nina Adgra,F,Newyork,31,2,Project12,1000000.0,Ongoing,0.0
10,A004,Nina Adgra,F,Newyork,31,2,Project13,3000000.0,Finished,150000.0
11,A005,Amy Johny,F,Madrid,30,3,Project5,NaN,Finished,NaN
12,A005,Amy Johny,F,Madrid,30,3,Project7,400000.0,Finished,20000.0
13,A005,Amy Johny,F,Madrid,30,3,Project14,200000.0,Finished,10000.0

In [20]:
# Add Mr. and Mrs. to Name
final["Name"] = np.where(final["Gender"] == "M",
                        "Mr. " + final["Name"],
                        "Mrs. " + final["Name"])

# Drop Gender column
final.drop("Gender", axis=1, inplace=True)

# Show updated dataframe
final

,ID,Name,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,Mr. John Alter,Paris,25,2,Project1,1002000.0,Finished,50100.0
1,A001,Mr. John Alter,Paris,25,2,Project9,NaN,Ongoing,0.0
2,A001,Mr. John Alter,Paris,25,3,Project11,2000000.0,Failed,0.0
3,A002,Mrs. Alice Luxumberg,London,27,2,Project2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice Luxumberg,London,27,3,Project6,680000.0,Failed,0.0
5,A003,Mr. Tom Sabestine,Berlin,29,3,Project3,4500000.0,Finished,225000.0
6,A003,Mr. Tom Sabestine,Berlin,29,4,Project8,350000.0,Failed,0.0
7,A003,Mr. Tom Sabestine,Berlin,29,3,Project10,300000.0,Finished,15000.0
8,A004,Mrs. Nina Adgra,Newyork,31,2,Project4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina Adgra,Newyork,31,2,Project12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina Adgra,Newyork,31,2,Project13,3000000.0,Finished,150000.0
11,A005,Mrs. Amy Johny,Madrid,30,3,Project5,NaN,Finished,NaN
12,A005,Mrs. Amy Johny,Madrid,30,3,Project7,400000.0,Finished,20000.0
13,A005,Mrs. Amy Johny,Madrid,30,3,Project14,200000.0,Finished,10000.0

In [21]:
# Promote designation level for age > 29
final.loc[final["Age"] > 29, "Designation Level"] -= 1

# Show updated dataframe
final

,ID,Name,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,Mr. John Alter,Paris,25,2,Project1,1002000.0,Finished,50100.0
1,A001,Mr. John Alter,Paris,25,2,Project9,NaN,Ongoing,0.0
2,A001,Mr. John Alter,Paris,25,3,Project11,2000000.0,Failed,0.0
3,A002,Mrs. Alice Luxumberg,London,27,2,Project2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice Luxumberg,London,27,3,Project6,680000.0,Failed,0.0
5,A003,Mr. Tom Sabestine,Berlin,29,3,Project3,4500000.0,Finished,225000.0
6,A003,Mr. Tom Sabestine,Berlin,29,4,Project8,350000.0,Failed,0.0
7,A003,Mr. Tom Sabestine,Berlin,29,3,Project10,300000.0,Finished,15000.0
8,A004,Mrs. Nina Adgra,Newyork,31,1,Project4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina Adgra,Newyork,31,1,Project12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina Adgra,Newyork,31,1,Project13,3000000.0,Finished,150000.0
11,A005,Mrs. Amy Johny,Madrid,30,2,Project5,NaN,Finished,NaN
12,A005,Mrs. Amy Johny,Madrid,30,2,Project7,400000.0,Finished,20000.0
13,A005,Mrs. Amy Johny,Madrid,30,2,Project14,200000.0,Finished,10000.0

In [22]:
# Calculate total project cost per employee
total_proj_cost = final.groupby(["ID", "Name"])["Cost"].sum().reset_index()

# Rename column
total_proj_cost.rename(columns={"Cost": "Total Cost"}, inplace=True)

# Show result
total_proj_cost

     ID                  Name  Total Cost
0  A001        Mr. John Alter   3002000.0
1  A002  Mrs. Alice Luxumberg   2680000.0
2  A003     Mr. Tom Sabestine   5150000.0
3  A004       Mrs. Nina Adgra   9500000.0
4  A005        Mrs. Amy Johny    600000.0

In [23]:
# Filter employees whose city contains 'o'
result = final[final["City"].str.contains("o", case=False)]

# Show result
result

,ID,Name,City,Age,Designation Level,Project,Cost,Status,Bonus
3,A002,Mrs. Alice Luxumberg,London,27,2,Project2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice Luxumberg,London,27,3,Project6,680000.0,Failed,0.0
8,A004,Mrs. Nina Adgra,Newyork,31,1,Project4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina Adgra,Newyork,31,1,Project12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina Adgra,Newyork,31,1,Project13,3000000.0,Finished,150000.0